CREATE VIEW P AS 
SELECT O.DATE, O.TIME, OD.ORDER_DETAILS_ID, OD.ORDER_ID, OD.PIZZA_ID, PT.PIZZA_TYPE_ID, PT.NAME, 
PT.CATEGORY, PT.INGREDIENTS, P.SIZE, OD.QUANTITY, P.PRICE, (OD.QUANTITY * P.PRICE) AS TOTAL_PRICE
FROM ORDER_DETAILS OD
JOIN ORDERS O ON OD.ORDER_ID = O.ORDER_ID 
JOIN PIZZAS P ON OD.PIZZA_ID = P.PIZZA_ID
JOIN PIZZA_TYPES PT ON PT.PIZZA_TYPE_ID = P.PIZZA_TYPE_ID;

-- 1. Most Selling Catagory of Pizza

SELECT CATEGORY, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER
FROM P
GROUP BY 1
ORDER BY 2 DESC;

-- 2. Most Selling Named of Pizza

SELECT NAME, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER
FROM P
GROUP BY 1
ORDER BY 2 DESC;

-- 3. Most Selling Size of Pizza

SELECT SIZE, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER
FROM P
GROUP BY 1
ORDER BY 2 DESC;

-- 4. Minimum and Maximum Date of Data

SELECT MIN(DATE), MAX(DATE)
FROM P;

-- 5. Most Selling Date of Pizza

SELECT DATE, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER
FROM P
GROUP BY 1
ORDER BY 2 DESC;

-- 6. Total Revenue

SELECT ROUND(SUM(TOTAL_PRICE),0) AS REVENUE
FROM P;

-- 7. Most Selling Month of Pizza

SELECT 
    DATE_FORMAT(DATE, '%M') AS START_OF_MONTH,
    ROUND(SUM(TOTAL_PRICE),0) AS REVENUE 
FROM P
GROUP BY DATE_FORMAT(DATE, '%M')
ORDER BY 2 DESC;

-- 8. Most Selling Time_Period of Pizza

SELECT 
    CASE 
        WHEN HOUR(TIME) BETWEEN 6 AND 13 THEN 'Morning'
        WHEN HOUR(TIME) BETWEEN 14 AND 21 THEN 'Evening'
        WHEN HOUR(TIME) BETWEEN 1 AND 5 OR HOUR(TIME) BETWEEN 22 AND 24 THEN 'Night'
    END AS TIME_PERIOD,
    ROUND(SUM(TOTAL_PRICE),0) AS REVENUE 
FROM P
GROUP BY TIME_PERIOD
ORDER BY 2 DESC;



select * from P








